HOLO-1365 / Explore Viem For Holograph SDK
holographxyz/holograph pull request #13
Opened 2024-02-09 18:22 UTC by BravoNatalie

## Describe Changes

Changes made to the package: **sdk**.

I made it better by doing ...

- Remove `ethers`
- Add `viem`

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Code styles have been enforced
- [ ] All tests are passing

2024-02-13 21:36 UTC, feliperodriguess requested changes

2024-02-13 21:36 UTC, feliperodriguess commented on packages/sdk/scripts/example.ts
> +  // console.log('providers: ', multiProviders.providers)
Can we remove these comments?

2024-02-13 21:36 UTC, feliperodriguess commented on packages/sdk/src/services/holograph-protocol.service.ts
> -  private operatorContract!: Operator
Why did you remove all the `Operator` references?

2024-02-14 13:17 UTC, BravoNatalie commented on packages/sdk/src/contracts/holograph.contract.ts
> +      // @ts-ignore
Couldn't get it to work, it's complaining about conflicting types.

2024-02-14 18:00 UTC, feliperodriguess approved these changes

2024-02-14 20:33 UTC, sogoiii approved these changes
👍 @BravoNatalie i love the encoder and decoder tests

2024-02-14 21:06 UTC, merged