Add README.md + general polishes
holographxyz/holograph pull request #88
Opened 2024-07-08 15:39 UTC by feliperodriguess

## Describe Changes

Changes made to the package: **sdk**.

I made it better by doing ...

- Add SDK README.md file with some guides
- Some general polishes on unnecessary properties/methods

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] Code styles have been enforced
- [x] All tests are passing

2024-07-08 23:00 UTC, sogoiii requested changes
Can we update to the latest 9 version of pnpm. You will have to update the `package.json` and the `.tool-versions` file.

2024-07-08 23:20 UTC, feliperodriguess commented on README.md
> +$ npm i @holographxyz/sdk @holographxyz/networks @holographxyz/environment
it works, we use yarn on our FE

2024-07-08 23:20 UTC, feliperodriguess commented on packages/sdk/package.json
> +  "version": "0.1.0-alpha.81",
sure

2024-07-09 04:29 UTC, feliperodriguess commented
> Can we update to the latest 9 version of pnpm. You will have to update the `package.json` and the `.tool-versions` file.

Done

2024-07-09 06:16 UTC, sogoiii approved these changes

2024-07-09 16:25 UTC, merged